In [4]:
'''NumPy is a Python package. It stands for 'Numerical Python'. 
It is a library consisting of multidimensional array objects and a collection of routines for processing of array.
There are many contributors to this open source project.
'''

"NumPy is a Python package. It stands for 'Numerical Python'. \nIt is a library consisting of multidimensional array objects and a collection of routines for processing of array.\nThere are many contributors to this open source project.\n"

In [8]:
#pip install numpy
import numpy as np 
a = np.array([1,2,3])   #single dimension array
a

array([1, 2, 3])

In [2]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [6]:
# minimum dimensions 
import numpy as np
a = np.array([1, 2, 3,4,5], ndmin = 5) 
print(a)

[[[[[1 2 3 4 5]]]]]


In [35]:
# dtype parameter 
import numpy as np
a = np.array([1, 2, 3], dtype = str) 
a

array(['1', '2', '3'], dtype='<U1')

In [39]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]])  #coloums nd rows shape
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [37]:
s=np.array([1,2,3,4,5,6])  # 6 2*3 3*2
s.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
q=np.array([1,2,3,4,5,6,7,8])
q.reshape(1,8)

q.reshape(8,1)
q.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(1,100,2) 
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [40]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
import numpy as np 
import warnings
warnings.filterwarnings('ignore')
x = np.zeros((9), dtype = int) 
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones((5),dtype = int)
x

array([1, 1, 1, 1, 1])

#### import numpy as np 
x = np.ones([2,3], dtype = int) 
x

In [113]:
# convert list to ndarray     by using asarray function
import numpy as np 
d={'name':'vineeth','roll':1} #dict to array convert
c=[1,5,5.5,True,1+5j,"python"]#default convert to string when we take list elements
e=(1,3,2,52,6,4,5)             #tuple convert
a=np.asarray(d)
a=np.asarray(e)
a

array([ 1,  3,  2, 52,  6,  4,  5])

In [42]:
# ndarray from list of tuples      by using asarray function
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
a

F:\vineethreddy\lib\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)


array([(1, 2, 3), (4, 5)], dtype=object)

In [43]:
import numpy as np 
x = np.arange(0,50,2) #by using range function  to print the looping of elements by jumping
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [110]:
import numpy as np 
# dtype set 
x = np.arange((50), dtype = float) # arange  function dtype conversion to float nd int
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [51]:
## indexing elements will be slice by using slicing function to jump elements
import numpy as np      
a = np.arange(10)
print(a)
s = slice(3,9,2)   #using slice function
a[s]


[0 1 2 3 4 5 6 7 8 9]


array([3, 5, 7])

In [116]:
import numpy as np 
a = np.arange(20) 
b = a[3:19:3]  #using list function in of slicing between elements
b

array([ 3,  6,  9, 12, 15, 18])

In [125]:
import numpy as np 
                              #addition,multiplication,division,subtractation,modules in ndarrays
a = np.array([145,2,300,4]) 
b = np.array([10,20,30,40]) 
c = a+b 
c

array([155,  22, 330,  44])

In [149]:
import numpy as np
a = np.arange(0,60,5)
print(a)
print('original iterate')
b=a.reshape(4,3)
print(b)
print('\n')
print('modifier array is')
for x in np.nditer(b):
    print (x)



[ 0  5 10 15 20 25 30 35 40 45 50 55]
original iterate
[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]]


modifier array is
0
5
10
15
20
25
30
35
40
45
50
55


In [155]:
import numpy as np 
a = np.array([0,30,45,60,90]) 

print('Sine of different angles:')
# Convert to radians by multiplying with pi/180 
print(np.sin(a*np.pi/180) )
print('\n')

print('Cosine values for angles in array:')
print(np.cos(a*np.pi/180) )
print('\n')  

print('Tangent values for given angles:')
print(np.tan(a*np.pi/180))


Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [197]:
import numpy as np 
a = np.arange(9, dtype = float).reshape(3,3)

print('First array:') 
print(a) 
print('\n')  

print('Second array:')
b = np.array([10,10,10]) 
print(b)
print('\n')  

print('Add the two arrays:') 
print(np.add(a,b)) 
print('\n')  

print('Subtract the two arrays:' )
print(np.subtract(a,b) )
print('\n')  

print('Multiply the two arrays:' )
print(np.multiply(a,b)) 
print('\n')  

print('Divide the two arrays:' )
print(np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply the two arrays:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [198]:
import numpy as np
a=np.array([1,2,3,4,5,6,1,4,2,5,4,1,4,41])
a=a.reshape(2,7)
print('1st array')
print(a)
print('\n')
b=np.array([1,5,4,6,2,54,52])
print('second array')
print(b)
print('\n')

print('addition a,b')
print(np.add(a,b))
print('\n')


print('multiplycation a,b')
print(np.multiply(a,b))
print('\n')

print('division a,b')
print(np.divide(a,b))
print('\n')

print('subtract a,b')
print(np.subtract(a,b))
print('\n')

1st array
[[ 1  2  3  4  5  6  1]
 [ 4  2  5  4  1  4 41]]


second array
[ 1  5  4  6  2 54 52]


addition a,b
[[ 2  7  7 10  7 60 53]
 [ 5  7  9 10  3 58 93]]


multiplycation a,b
[[   1   10   12   24   10  324   52]
 [   4   10   20   24    2  216 2132]]


division a,b
[[1.         0.4        0.75       0.66666667 2.5        0.11111111
  0.01923077]
 [4.         0.4        1.25       0.66666667 0.5        0.07407407
  0.78846154]]


subtract a,b
[[  0  -3  -1  -2   3 -48 -51]
 [  3  -3   1  -2  -1 -50 -11]]




In [169]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print('Our array is:') 
print(a ) 
print('\n')


print('Applying amin() function again:' )
print(np.amin(a,0) )
print('\n' )


print('Applying amax() function again:')
print(np.amax(a, axis = 1))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function again:
[2 4 3]


Applying amax() function again:
[7 8 9]


In [54]:
import numpy as np  
a = np.array([[3,7],[9,1]]) 

print('Our array is:') 
print(a)
print('\n')

print('Applying sort() function:')
print(np.sort(a)) 
print('\n') 
  
print('Sort along axis 0:') 
print(np.sort(a, axis = 0))
print('\n')  


Our array is:
[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Sort along axis 0:
[[3 1]
 [9 7]]




In [8]:
import numpy as np
  
a= np.array([5], dtype =float)
  
g = a.itemsize
  
g

8

In [209]:

# numpy.sqrt() method

# importing numpy
import numpy as k

# applying sqrt() method on integer numbers
arr1 = k.sqrt([1, 4, 9, 16])
arr2 = k.sqrt([6, 10, 18])

print("square-root of an array1 : ", arr1)
print("square-root of an array2 : ", arr2)


square-root of an array1 :  [1. 2. 3. 4.]
square-root of an array2 :  [2.44948974 3.16227766 4.24264069]


In [18]:
# Python Program illustrating
# numpy.sum() method
import numpy as np
# 1D array
arr = [20, 2, .2, 10, 4]

print("Sum of arr : ", np.sum(arr))

print("Sum of arr(uint8) : ", np.sum(arr, dtype = np.uint8))
print("Sum of arr(float32) : ", np.sum(arr, dtype = np.float32))




Sum of arr :  36.2
Sum of arr(uint8) :  36
Sum of arr(float32) :  36.2


In [1]:

# numpy.sum() method
import numpy as np
# 2D array
arr = np.array([[14, 17, 12, 33, 44],[15, 6, 27, 8, 19]])
print(arr)

print("\nSum of arr : ", np.sum(arr))
print("Sum of arr(axis = 0) : ", np.sum(arr, axis = 0))
print("Sum of arr(axis = 1) : ", np.sum(arr, axis = 1))




[[14 17 12 33 44]
 [15  6 27  8 19]]

Sum of arr :  195
Sum of arr(axis = 0) :  [29 23 39 41 63]
Sum of arr(axis = 1) :  [120  75]


In [ ]:
#task 19
numpy practise
