# Numpy in python 

# Array

In [1]:
# install the numpy
# !pip install numpy

In [2]:
#import the numpy
import numpy as np # np is alias name for shortcut

In [8]:
my_lst = [1,2,3,4,5] #list creating 
arr = np.array(my_lst) #converting to numpy arrays

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape  #shape of the array

(5,)

In [10]:
arr.reshape(1,5) #reshape array  it means converting 1D to 2D array or  multi dimensional array

array([[1, 2, 3, 4, 5]])

In [14]:
#creating the multi dimensional arrays
my_list1 = [1,2,3,4,5,6]
my_list2 = [7,8,9,10,11,12]   #creating lists
my_list3 = [12,11,10,9,8,7]

arr1 = np.array([my_list1,my_list2,my_list3])  #converting to nd array

In [16]:
arr1 # printing the multi dimensional array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [12, 11, 10,  9,  8,  7]])

In [17]:
arr1.shape

(3, 6)

In [35]:
#creating the ndmin for no of dimensions
arr2 = np.array([1,2,3,4,5,6,7,8,9],ndmin = 3) #arr2 creating ndimensions so use ndmin = n no of dimensions

In [36]:
arr2

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [41]:
# this is the one of the creting multi dimensions
my_list4 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,67]])

#NOTE : when we create the multi dimensions  that time we have to check the  no of rows and columns are will be the same 

In [42]:
my_list4

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  2,  3,  4,  5, 67]])

In [53]:
new_array = np.array([[2,4,6,7,8,9,10,2],[1,2,3,4,5,6,7,8],[2,3,4,6,7,8,6,7]]) # creating multi dimension array

In [54]:
new_array

array([[ 2,  4,  6,  7,  8,  9, 10,  2],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  6,  7,  8,  6,  7]])

In [57]:
new_array.shape # check the shape of rows and columns

(3, 8)

In [61]:
new_array.reshape(6,4)  # total 24 elements are there  so we multiple with two numbers and out wil be 24 so 
                        # we can take as (6,4),(4,6),(12,2),(2,12),(1,24)(24,1) these element values sholud be classify reshape

array([[ 2,  4,  6,  7],
       [ 8,  9, 10,  2],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2,  3,  4,  6],
       [ 7,  8,  6,  7]])

# Indexing in single dimension array

In [77]:
my_lst = [1,2,3,4,5] #list creating 
arr = np.array(my_lst) #converting to numpy arrays

In [78]:
arr

array([1, 2, 3, 4, 5])

In [79]:
arr[0] #we will use this one dimensions array for finding the indexing value

1

# Indexing in multiple  dimension array

In [82]:
new_array = np.array([[2,4,6,7,8,9,10,2],[1,2,3,4,5,6,7,8],[2,3,4,6,7,8,6,7]]) # creating multi dimension array

In [85]:
new_array[:] # printing all indexing values

array([[ 2,  4,  6,  7,  8,  9, 10,  2],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  6,  7,  8,  6,  7]])

In [86]:
new_array[:,:] # printing left and right indexing values

array([[ 2,  4,  6,  7,  8,  9, 10,  2],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  6,  7,  8,  6,  7]])

In [91]:
new_array[:,3:] # printing after 3 number indexing values(after 3 Right side values are printed)

array([[ 7,  8,  9, 10,  2],
       [ 4,  5,  6,  7,  8],
       [ 6,  7,  8,  6,  7]])

In [92]:
new_array[: , :3] # printing before 3 number indexing values(before 3 Right side values are printed)

array([[2, 4, 6],
       [1, 2, 3],
       [2, 3, 4]])

In [111]:
new_array[: , :-1]  # printing the leaving the last indexing values and -1 come to from reverse

array([[ 2,  4,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  3,  4,  6,  7,  8,  6]])

In [152]:
new_arrange = np.arange(0,20,2) # as like range funtion in python incase in numpy we will use arrange function to range of numbers

In [153]:
new_arrange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [154]:
np.linspace(0,10,5)  # linspace is used to the step values between range functon

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [155]:
new_arrange

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [156]:
new_arrange[6] =2   #broadcasting  function is used to changing the values in certain indexing elemenmts

In [157]:
new_arrange

array([ 0,  2,  4,  6,  8, 10,  2, 14, 16, 18])

In [160]:
#some conditions very useful in EDA(Exploratory Data Analysis)
val = 2
new_arrange[new_arrange<=val]

array([0, 2, 2])

In [161]:
new_array = np.array([[2,4,6,7,8,9,10,2],[1,2,3,4,5,6,7,8],[2,3,4,6,7,8,6,7]]) # creating multi dimension array

In [162]:
new_array

array([[ 2,  4,  6,  7,  8,  9, 10,  2],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  6,  7,  8,  6,  7]])

In [179]:
#some conditions very useful in EDA(Exploratory Data Analysis)
val = 5
print ('greaterthan eql to 5 numbers in array',new_array[new_array>=val])
print('\n')
print ('lessthan eql to 5 numbers in array',new_array[new_array<=val])
print('\n')
print ('eql to 5 numbers in array',new_array[new_array==val])
print('\n')
print ('greaterthan to 5 numbers in array',new_array[new_array>val])
print('\n')
print ('less than eql to 5 numbers in array',new_array[new_array<val])

greaterthan eql to 5 numbers in array [ 6  7  8  9 10  5  6  7  8  6  7  8  6  7]


lessthan eql to 5 numbers in array [2 4 2 1 2 3 4 5 2 3 4]


eql to 5 numbers in array [5]


greaterthan to 5 numbers in array [ 6  7  8  9 10  6  7  8  6  7  8  6  7]


less than eql to 5 numbers in array [2 4 2 1 2 3 4 2 3 4]


In [184]:
arr_1 = np.arange(0,10).reshape(2,5)
arr_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [185]:
arr_2 = np.arange(0,10).reshape(2,5)
arr_2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [187]:
arr_1*arr_2     #multiplying two arrays

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [209]:
np.zeros((5,5),dtype=int) #all ones in multi dimensions 

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [207]:
np.ones((5,5),dtype=int)  #all  Zeros in multi dimensions

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [218]:
#random distribution in numpy
np.random.rand(1,10)  #in rand as 1 * 10  uniform distribution like 0 to 1 range between values to 10 

array([[0.33845772, 0.2844579 , 0.21974766, 0.03158805, 0.12979426,
        0.43680165, 0.31962937, 0.05880605, 0.57804188, 0.58256717]])

In [224]:
arr_ex = np.random.randn(4,4) # standard normal distribution - to + values

In [225]:
arr_ex

array([[-0.18779462,  2.08280479, -0.35558539, -0.02663217],
       [-0.839743  , -0.38666955, -2.2466371 ,  1.25008995],
       [-0.60747729,  1.02170982, -0.12017969,  0.2489043 ],
       [ 0.50612025,  1.15798139,  0.17185007,  0.42456503]])

In [241]:
np.random.random_sample((1,2)) #it is also floats values betweeen range of 0 to 1

array([[0.16990202, 0.64804799]])

In [243]:
np.random.randint(0,20,size=10).reshape(2,5)   # randomly integer values are implemented the range of values 

array([[ 6,  6,  8, 10, 11],
       [19, 14, 19,  5,  9]])

In [244]:
new_array

array([[ 2,  4,  6,  7,  8,  9, 10,  2],
       [ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  6,  7,  8,  6,  7]])

In [255]:
new_array[1:,5:]   # semicolumn will have left side of the indexing number that before indexing values are printed 
                    # semicolumn will have right side of the indexing number that after indexing values are printed 
                    #this is the indexing values atre printed by rows and columns like as  left is rows and right is columns

array([[6, 7, 8],
       [8, 6, 7]])

In [256]:
new_array.T      #transpose function is work like a transpose matrix

array([[ 2,  1,  2],
       [ 4,  2,  3],
       [ 6,  3,  4],
       [ 7,  4,  6],
       [ 8,  5,  7],
       [ 9,  6,  8],
       [10,  7,  6],
       [ 2,  8,  7]])

In [268]:
a = np.arange(1,10)
b = np.arange(10)
c = np.arange(10)
np.concatenate((a,b,c)) #joining the arrays

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2,
       3, 4, 5, 6, 7, 8, 9])

In [270]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2]])

In [275]:
np.concatenate((a,b.T),axis = 1)     #transpose array

array([[1, 2, 1],
       [3, 4, 2]])

In [276]:
np.vstack((a,b)) # same as works like concat 

array([[1, 2],
       [3, 4],
       [1, 2]])

In [286]:
a = np.arange(1,13)
np.split(a,4)  #splitting the array by 4
np.split(a,2)   #splitting the array by 2

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]

In [288]:
# insert function in numpy 
a = np.arange(0,10)
np.insert(a,5,500)     #inserting in 5th index element

array([  0,   1,   2,   3,   4, 500,   5,   6,   7,   8,   9])

In [294]:
np.insert(a,(3,10),500)  #inserting in two indexing elements 

array([  0,   1,   2, 500,   3,   4,   5,   6,   7,   8,   9, 500])

# Matrix

In [301]:
a =np.matrix("2 4 ; 5 10")

In [302]:
a

matrix([[ 2,  4],
        [ 5, 10]])

In [305]:
b =np.matrix("2 4 ; 5 10")
b

matrix([[ 2,  4],
        [ 5, 10]])

In [307]:
a+b    #addition in matrix

matrix([[ 4,  8],
        [10, 20]])

In [310]:
a*b #multiplication

matrix([[ 24,  48],
        [ 60, 120]])

In [312]:
a-b  #subtraction

matrix([[0, 0],
        [0, 0]])

In [313]:
a%b #moduules matrix

matrix([[0, 0],
        [0, 0]], dtype=int32)

In [315]:
a // b  #division matraix

matrix([[1, 1],
        [1, 1]], dtype=int32)

# Linear Algebra

Inverse Matrix

In [326]:
#inverse matrix 
a = np.array([[1,2],[3,4]])   

In [327]:
b = np.linalg.inv(a) #inverse of matrix is the worked on 1/ad-bc[d -b,-c a]

In [328]:
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [330]:
np.allclose(np.dot(a,b),np.eye(2))   #dot product

True

In [331]:
np.dot(a,b)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

Power Of Matrix A 

In [342]:
a = np.array([[1,2],[3,4]])   
np.linalg.matrix_power(a,0)   #syntax of power matrix  #a2 is a power of matrix

array([[1, 0],
       [0, 1]])

In [341]:
np.dot(a,a)      #a * a is a power of matrix so we can use dot product

array([[ 7, 10],
       [15, 22]])

In [344]:
np.dot(a,2)     #dot product means matrix square is a^2

array([[2, 4],
       [6, 8]])

solve linear eqn in numpy as mtrix

In [370]:
a = np.matrix('3 1 ; 1 2')      

In [371]:
b = np.matrix('9;8')

In [372]:
a,b    # 3x + y = 9      
       # x + 2y = 8

(matrix([[3, 1],
         [1, 2]]),
 matrix([[9],
         [8]]))

In [373]:
# solved  the above equation by using numpy library in linalg.solve
np.linalg.solve(a,b)   # syntax of inversre method    

matrix([[2.],
        [3.]])

Determinant of a Matrix

In [374]:
# the formula of determinant of matrix is ad - bc 
a = np.array([[1,2],[3,4]])
np.linalg.det(a)  #syntax of det

-2.0000000000000004

In [375]:
round(np.linalg.det(a))   #round up number 

-2